export {
  INTEL_LIMITS,
  ROOM_INTEL_SCHEMA_VERSION,
  createRoomIntelCodec,
  projectRoomIntelRecord,
  validRoomIntelRecord,
  type IntelCollectionStatus,
  type RoomIntelController,
  type RoomIntelHostile,
  type RoomIntelMineral,
  type RoomIntelPosition,
  type RoomIntelRecordV1,
  type RoomIntelSource,
  type RoomIntelStructure,
} from "./room-intel";

export {
  INTEL_SERVICE_LIMITS,
  IntelService,
  emptyIntelRuntimeResult,
  type IntelRuntimeResult,
  type IntelServiceMetrics,
  type RoomIntelFreshness,
  type RoomIntelQuality,
  type RoomIntelQuery,
  type RoomIntelQueryReason,
  type RoomIntelQueryResult,
  type RoomIntelRouteQuery,
  type RoomIntelRouteResult,
  type ScoutVisionRequestV1,
  type VisionDemandDisposition,
  type VisionDemandReason,
  type VisionDemandV1,
  type VisionRefreshProjection,
  type VisionScoutAuthorization,
} from "./service";
